# Generated by Django 5.2.4 on 2025-08-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='URL')),
                ('continent', models.CharField(choices=[('Europe', 'Европа'), ('Asia', 'Азия'), ('North America', 'Северная Америка'), ('South America', 'Южная Америка'), ('Africa', 'Африка'), ('Oceania', 'Океания')], max_length=50, verbose_name='Континент')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('population_mil', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Население (млн)')),
                ('area_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь (км²)')),
                ('gdp_usd', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='ВВП ($)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ['title'],
            },
        ),
    ]
