# Generated by Django 5.2.4 on 2025-08-06 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (USD)')),
                ('bookings', models.PositiveIntegerField(default=0, verbose_name='Количество броней')),
                ('days', models.PositiveIntegerField(default=1, verbose_name='Дней тура')),
                ('includes_flight', models.BooleanField(default=True, verbose_name='Включён перелёт')),
                ('includes_hotel', models.BooleanField(default=True, verbose_name='Включён отель')),
                ('includes_excursions', models.BooleanField(default=True, verbose_name='Включены экскурсии')),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/', verbose_name='Изображение')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_offers', to='main.destination')),
            ],
        ),
    ]
